//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SupplierEvaluation
{
    using System;
    using System.Collections.Generic;
    
    public partial class AL_Vendor
    {
        public string Vender { get; set; }
        public string VenderName { get; set; }
        public string AbbreName { get; set; }
        public string Route { get; set; }
        public string Currency { get; set; }
        public string EMailPO { get; set; }
        public string BOIType { get; set; }
        public string PersonIncharge { get; set; }
        public Nullable<bool> isMilkRun { get; set; }
        public string VenderCard { get; set; }
    }
}
