//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SupplierEvaluation
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class dbIoTFac2Entities : DbContext
    {
        public dbIoTFac2Entities()
            : base("name=dbIoTFac2Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<etd_model_detail> etd_model_detail { get; set; }
        public virtual DbSet<etd_mst_model> etd_mst_model { get; set; }
        public virtual DbSet<etd_mst_program> etd_mst_program { get; set; }
        public virtual DbSet<etd_program_detail> etd_program_detail { get; set; }
    }
}
