//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SupplierEvaluation
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public string CODE { get; set; }
        public string PREN { get; set; }
        public string NAME { get; set; }
        public string SURN { get; set; }
        public string SEX { get; set; }
        public string TPREN { get; set; }
        public string TNAME { get; set; }
        public string TSURN { get; set; }
        public string TSEX { get; set; }
        public Nullable<System.DateTime> BIRTH { get; set; }
        public Nullable<System.DateTime> JOIN { get; set; }
        public Nullable<System.DateTime> RESIGN { get; set; }
        public string RELIGION { get; set; }
        public string RSTYPE { get; set; }
        public string DVCD { get; set; }
        public string WTYPE { get; set; }
        public string WSTS { get; set; }
        public string POSIT { get; set; }
        public string P_RANK { get; set; }
        public string P_GRADE { get; set; }
        public string BUS { get; set; }
        public string STOP { get; set; }
        public string TCADDR3 { get; set; }
        public string TCADDR4 { get; set; }
        public string TCTEL { get; set; }
        public string TELEPHONE { get; set; }
        public string MAIL { get; set; }
        public string OTYPE { get; set; }
        public string DLRATE { get; set; }
        public string GRPOT { get; set; }
        public string NICKNAME { get; set; }
        public string COSTCENTER { get; set; }
        public string COMPANY { get; set; }
        public string TPOSINAME { get; set; }
        public Nullable<System.DateTime> TPOSIJOIN_DT { get; set; }
        public Nullable<System.DateTime> ANNUALCAL_DT { get; set; }
        public string ANDON { get; set; }
        public string LOCATION { get; set; }
        public string WORKCENTER { get; set; }
        public string BUDGETTYPE { get; set; }
        public string LineCode { get; set; }
    }
}
