//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SupplierEvaluation
{
    using System;
    using System.Collections.Generic;
    
    public partial class etd_model_detail
    {
        public string m_id { get; set; }
        public string p_id { get; set; }
        public string pt_id { get; set; }
        public string r_id { get; set; }
        public double p_mid_dimension { get; set; }
        public double p_max_dimension { get; set; }
        public double p_min_dimension { get; set; }
        public double p_cycletime { get; set; }
        public System.DateTime p_date { get; set; }
        public string p_user { get; set; }
        public bool p_status { get; set; }
    }
}
