//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SupplierEvaluation
{
    using System;
    using System.Collections.Generic;
    
    public partial class etd_mst_model
    {
        public string m_id { get; set; }
        public string m_name { get; set; }
        public System.DateTime m_date { get; set; }
        public string m_user { get; set; }
    }
}
