//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SupplierEvaluation
{
    using System;
    using System.Collections.Generic;
    
    public partial class etd_mst_program
    {
        public int pro_id { get; set; }
        public string pro_name { get; set; }
        public string yc { get; set; }
    }
}
