//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SupplierEvaluation
{
    using System;
    using System.Collections.Generic;
    
    public partial class PU_EvaluateSupplier
    {
        public int id { get; set; }
        public string vd_addr { get; set; }
        public string EInvoice { get; set; }
        public string rnd_invno_sup { get; set; }
        public System.DateTime rnd_date { get; set; }
        public string rnd_time { get; set; }
        public string Comment { get; set; }
        public string Remark { get; set; }
        public decimal point { get; set; }
        public string Type { get; set; }
        public string InputType { get; set; }
        public string Status { get; set; }
        public string CreateBy { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string UpdateBy { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
    }
}
