//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SupplierEvaluation
{
    using System;
    using System.Collections.Generic;
    
    public partial class PU_EvaluateSupplierResult
    {
        public int id { get; set; }
        public string datayear { get; set; }
        public string datamonth { get; set; }
        public string SupplierNO { get; set; }
        public Nullable<decimal> delivery_point { get; set; }
        public Nullable<decimal> document_point { get; set; }
        public Nullable<decimal> correct_point { get; set; }
        public Nullable<decimal> safety_point { get; set; }
        public Nullable<decimal> result_point { get; set; }
        public string result_grade { get; set; }
        public string UpdateBy { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
    }
}
